"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
continuation_prompt = "[.](green) "
palette = "default"

format = """
[╭─](fg:bg)\
[ ](bg:bg)\
$os\
$hostname\
$username\
$directory\
$nodejs\
$git_branch\
$git_status\
[ ](fg:bg)\
( ?? $all)\
$fill\
[](fg:bg)\
$character\
$cmd_duration\
$time\
$line_break\
[╰─](fg:bg)\
[❯ ](fg:bg)"""

[palettes.default]
bg = "#444444"
sep = "#858584"

[fill]
symbol = ' '

[aws]
disabled = true
symbol = "  "

[directory]
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"
read_only = " 󰌾"
style = "bg:bg #0087ae"
before_repo_root_style = "bg:bg #0087ae"
repo_root_style = "bg:bg bold #03aefe"
truncate_to_repo = false
truncation_length = 0
use_os_path_sep = false

[docker_context]
symbol = " "

[dotnet]
disabled = true

[git_branch]
format = "[[](bg:bg fg:sep) $symbol$branch(:$remote_branch) ]($style)"
style = "bg:bg fg:#5fd701"
symbol = " "

[git_status]
ahead = "[⇡${count} ](bg:bg green)"
behind = "[⇣${count} ](bg:bg red)"
deleted = ""
up_to_date = ""
diverged = "[${behind_count}](bg:bg red)[ ](bg:bg)[${ahead_count}](bg:bg green)[ ](bg:bg)"
format = "([$ahead_behind$all_status]($style))"
modified = "[!${count} ](bg:bg yellow)"
renamed = "[~](bg:bg green)"
staged = "[+${count} ](bg:bg yellow)"
stashed = ""
style = "bg:bg"
untracked = "[?${count} ](bg:bg #03aefe)"

[golang]
symbol = " "

[hostname]
disabled = true
format = "[$ssh_symbol$hostname ]($style)"
ssh_only = false
ssh_symbol = " "
style = "bg:bg white"

[java]
symbol = " "

[nodejs]
format = "[[](bg:bg fg:sep)  $version ](bg:bg $style)"
not_capable_style = "red"
style = "green"

[os]
disabled = true
format = "[ $symbol ]($style)"
style = "bg:bg white"

[os.symbols]
Linux = ""
Macos = ""
Windows = ""

[package]
symbol = "󰏗 "

[python]
symbol = " "

[username]
disabled=true
format = "[[](bg:bg fg:sep)  $user ](bg:bg $style)"
show_always = true
style_root = "red"
style_user = "white"

[character]
format = '$symbol'
success_symbol = '[ ✔ ](bg:bg bold #5fd701)'
error_symbol = '[ ✘ ](bg:bg bold #d71e01)'

[cmd_duration]
disabled = false
format = "[[](bg:bg fg:sep) $duration ](bg:bg #a8a9a9)"
min_time = 2_000

[time]
disabled = false
time_format = "%T"
utc_time_offset = "local"
format = '[[](bg:bg fg:sep) $time ](bg:bg #5e8789)'
